name: "Slack notify"
description: "Hellp"
author: "Zomzog@gmail.com"

inputs:
  BRANCH_NAME:
    description: "Branch name"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "bell"
  color: "yellow"